FROM docker.io/savonet/liquidsoap:v2.4.5

ENTRYPOINT []

# Sync liquidsoap uid/gid with the host account
USER root

RUN set -ex; \
    groupadd -g 1021 na-stream && \
    usermod -u 1021 -g 1021 liquidsoap && \
    chown -R 1021:1021 /var/cache/liquidsoap

USER liquidsoap

CMD ["/usr/bin/liquidsoap", "/etc/liquidsoap/noagenda.liq"]
