# % -- include/secrets.liq -- %
# vim: ft=liq ts=4 sw=4 sts=2 et ai fdm=marker

# All the paths will be prefixed with this path
basepath = "/stor/nastream"

# Stream private info
streammount = "somemount"
musicmount  = "musicmount"
streampass  = "somepass"
inpass      = "srcpass"

streamport  = 3040
adam_inport = 4700
horo_inport = 4702
also_inport = 4704
noop_inport = 4800

nastream1_name = "alpha"
nastream2_name = "beta"
nastream3_name = "delta"
nastream4_name = "gamma"

nastream1_host = "nastream1.example.com"
nastream2_host = "nastream2.example.com"
nastream3_host = "nastream3.example.com"
nastream4_host = "nastream4.example.com"
