# % -- include/secrets.liq -- %
# vim: ft=liq ts=4 sw=4 sts=2 et ai fdm=marker

# All the paths will be prefixed with this path
basepath = "/stor/nastream"

# Stream private info
streammount = "somemount"
streampass  = "somepass"
inpass      = "srcpass"
streamport  = 3040
adam_inport = 4700
horo_inport = 4702
also_inport = 4704
noop_inport = 4800
nastream1   = "stream1.example.com"
nastream2   = "stream2.example.com"
nastream3   = "stream3.example.com"
